### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by Ede1994** [UCL/pet-rd-tools#44]
I've some problems, when I run make in the pet-rd-tools-master (see error_file.txt). Can anyone help me with some infos about the installation? I've installed all requirements. 
[error_file.txt](https://github.com/UCL/pet-rd-tools/files/4856865/error_file.txt)

**Comment by KrisThielemans** [comment]
error is
```
/usr/bin/ld: -lglog::glog cannot be found
```
this seems to say it's interpreting the CMake target as a file, which is obviously incorrect.

If on Linux, you could try `sudo apt install libgoogle-glog-dev` if you didn't yet. Might be good to use a new CMake as well.

Otherwise, give more info on your configuration, including OS, CMake, glog and pet-rd-tools version.

An alternative might be to use the [SIRF-SuperBuild](https://github.com/SyneRBI/SIRF-SuperBuild) which will build glog and pet-rd-tools.

**Comment by Ede1994** [comment]
I tried to use nm_extract etc with the SIRF-SuperBuild but it didn't work. So I searched for another way...

How can I use nm_extract etc with the SIRF-SuperBuild?

**Comment by KrisThielemans** [comment]
Setting `BUILD_pet_rd_tools=ON` with CMake should do the trick. e.g. command line 
```sh
cd whereveryoubuiltthesuperbuild
cmake -DBUILD_pet_rd_tools:BOOL=ON .
make pet-rd-tools
```
(I'm being optimistic)

**Comment by Ede1994** [comment]
That works! Thanks!
